### PR TITLE
Subversion loading rejig

### LINKED ISSUE #21: Subversion patches should be able to tell the ModLoader when do they want to be loaded
#12 but proper.

SubversionPatch class should have a boolean that determines if the dll is getting loaded *before* or *after* the content pack.
Currently the logic has been set to load after the content pack, see commit https://github.com/ValidHunters/Marseyloader/commit/fb0c4e8d2578d9abe9a40617e2989d3cb9dd64bd.

### LINKED ISSUE #31: Allow sideloaded mods to be reflected by the engine under hidesey
Currently subversion relies on a few reflection-related tricks via MarseyEntry to add own commands, components and systems when running under unconditional.

### PR DESCRIPTION
**Pull request by Subversionary**
Slightly altered patch logic:

* Sideloading is now executed twice - before and after the game's assemblies have been loaded
* This behavior is determined by the preload value, which is by default set to true if missing
* Sideloaded assemblies will be hidden just before EntryPoint kicks in

Resolves #31 
Resolves #21

### CODE REVIEW

**Comment by Subversionary** [comment]
Simple command sideloaded patches seem to be working fine, anything more complex (UI fuckery, for example) does not reflect in time and breaks

**Comment by Subversionary** [comment]
> This pull request has conflicts, please resolve those before we can evaluate the pull request.


https://github.com/ValidHunters/Marseyloader/assets/109166122/5fbe63ae-dc4d-4cbc-b42f-ce3ab50d84b7

**Comment by Subversionary** [comment]
> This pull request has conflicts, please resolve those before we can evaluate the pull request.


https://github.com/ValidHunters/Marseyloader/assets/109166122/9b5bc336-f3f7-47d3-8354-5629a49d5a3e

**Comment by mrsteyk** [comment]
Me when I am evaluating this pull request.
chenstarejif_1

**Comment by Subversionary** [comment]
> Me when I am evaluating this pull request. chenstarejif_1 [ chenstarejif_1 ](https://private-user-images.githubusercontent.com/10615163/331882775-e1e14045-5b66-4b32-8c0f-1f31b324d653.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzMxNzIsIm5iZiI6MTcxNjEzMjg3MiwicGF0aCI6Ii8xMDYxNTE2My8zMzE4ODI3NzUtZTFlMTQwNDUtNWI2Ni00YjMyLThjMGYtMWYzMWIzMjRkNjUzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE1MzQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZmVkYjllNjQyNmQ3ZTNjYjQ1MWVlMjdlNzgwN2VjMGMwN2E5MGE1ZWRmYWQ0MzdmZDVmOWQzZGFhMWQzYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1rybksulsaYe0KnUAbE7lii1KtGx5Si_Wrg6i8m-Yuk) [ ](https://private-user-images.githubusercontent.com/10615163/331882775-e1e14045-5b66-4b32-8c0f-1f31b324d653.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzMxNzIsIm5iZiI6MTcxNjEzMjg3MiwicGF0aCI6Ii8xMDYxNTE2My8zMzE4ODI3NzUtZTFlMTQwNDUtNWI2Ni00YjMyLThjMGYtMWYzMWIzMjRkNjUzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE1MzQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZmVkYjllNjQyNmQ3ZTNjYjQ1MWVlMjdlNzgwN2VjMGMwN2E5MGE1ZWRmYWQ0MzdmZDVmOWQzZGFhMWQzYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1rybksulsaYe0KnUAbE7lii1KtGx5Si_Wrg6i8m-Yuk)


https://github.com/ValidHunters/Marseyloader/assets/109166122/7444130f-2f89-4901-b6fa-750b96d13ce9

**Comment by Subversionary** [comment]
ну давай-давай, evaluate

**Comment by Subversionary** [comment]
Implementation is flawed at the base level

**Pull request closed without merging**
